INFO 2024-04-09 22:30:15,500 views  Main page accessed
INFO 2024-04-09 22:30:15,500 basehttp  "GET / HTTP/1.1" 200 15
INFO 2024-04-09 22:30:23,776 views  Главная страница загружена
INFO 2024-04-09 22:30:23,777 basehttp  "GET / HTTP/1.1" 200 15
INFO 2024-04-09 22:30:25,812 views  Главная страница загружена
INFO 2024-04-09 22:30:25,813 basehttp  "GET / HTTP/1.1" 200 15
INFO 2024-04-09 22:30:26,748 views  Страница "о нас" загружена
INFO 2024-04-09 22:30:26,748 basehttp  "GET /about/ HTTP/1.1" 200 16
INFO 2024-04-09 22:39:21,279 autoreload  Watching for file changes with StatReloader
INFO 2024-04-09 22:39:29,261 views  Главная страница загружена
INFO 2024-04-09 22:39:29,262 basehttp  "GET / HTTP/1.1" 200 411
INFO 2024-04-09 22:39:45,462 views  Главная страница загружена
INFO 2024-04-09 22:39:45,462 basehttp  "GET / HTTP/1.1" 200 411
INFO 2024-04-09 22:39:47,971 views  Главная страница загружена
INFO 2024-04-09 22:39:47,972 basehttp  "GET / HTTP/1.1" 200 411
INFO 2024-04-09 22:39:49,101 views  Страница "о нас" загружена
INFO 2024-04-09 22:39:49,102 basehttp  "GET /about/ HTTP/1.1" 200 412
INFO 2024-04-09 22:47:13,568 autoreload  /Users/Asus/FrameworkDjango/Django_HW/django_homework/views.py changed, reloading.
INFO 2024-04-09 22:47:13,882 autoreload  Watching for file changes with StatReloader
INFO 2024-04-09 22:47:57,814 views  Main page accessed
INFO 2024-04-09 22:47:57,815 basehttp  "GET / HTTP/1.1" 200 707INFO 2024-04-13 05:42:49,671 autoreload  Watching for file changes with StatReloader
WARNING 2024-04-13 05:42:55,633 log  Not Found: /
WARNING 2024-04-13 05:42:55,633 basehttp  "GET / HTTP/1.1" 404 2790
WARNING 2024-04-13 05:42:55,722 log  Not Found: /favicon.ico
WARNING 2024-04-13 05:42:55,722 basehttp  "GET /favicon.ico HTTP/1.1" 404 2841
INFO 2024-04-13 05:43:25,972 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\urls.py changed, reloading.
INFO 2024-04-13 05:43:26,349 autoreload  Watching for file changes with StatReloader
INFO 2024-04-13 05:43:27,113 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-13 05:43:33,745 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-13 05:43:35,488 basehttp  "GET /about/ HTTP/1.1" 200 848
INFO 2024-04-13 05:43:36,643 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-13 05:43:37,619 basehttp  "GET /about/ HTTP/1.1" 200 848
INFO 2024-04-13 05:43:38,277 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-13 05:44:04,009 basehttp  "GET /app2 HTTP/1.1" 301 0
INFO 2024-04-13 05:44:04,012 basehttp  "GET /app2/ HTTP/1.1" 200 1080
INFO 2024-04-13 05:44:09,554 basehttp  "GET /app2/ HTTP/1.1" 200 1080
INFO 2024-04-13 05:44:41,532 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\urls.py changed, reloading.
INFO 2024-04-13 05:44:41,907 autoreload  Watching for file changes with StatReloader
INFO 2024-04-13 05:44:45,364 basehttp  "GET /app2/ HTTP/1.1" 200 1080
INFO 2024-04-13 05:44:46,088 basehttp  "GET /app2/ HTTP/1.1" 200 1080
INFO 2024-04-13 05:44:48,060 basehttp  "GET /app2/ HTTP/1.1" 200 1080
WARNING 2024-04-13 05:44:50,793 log  Not Found: /
WARNING 2024-04-13 05:44:50,794 basehttp  "GET / HTTP/1.1" 404 2686
WARNING 2024-04-13 05:44:52,013 log  Not Found: /
WARNING 2024-04-13 05:44:52,014 basehttp  "GET / HTTP/1.1" 404 2686
WARNING 2024-04-13 05:44:52,248 log  Not Found: /
WARNING 2024-04-13 05:44:52,250 basehttp  "GET / HTTP/1.1" 404 2686
WARNING 2024-04-13 05:44:52,475 log  Not Found: /
WARNING 2024-04-13 05:44:52,475 basehttp  "GET / HTTP/1.1" 404 2686
INFO 2024-04-13 05:45:17,024 autoreload  Watching for file changes with StatReloader
WARNING 2024-04-13 05:45:23,852 log  Not Found: /
WARNING 2024-04-13 05:45:23,852 basehttp  "GET / HTTP/1.1" 404 2686
WARNING 2024-04-13 06:12:34,069 log  Not Found: /app2/client
WARNING 2024-04-13 06:12:34,069 basehttp  "GET /app2/client HTTP/1.1" 404 2973
WARNING 2024-04-13 06:13:34,063 log  Not Found: /app2/clients
WARNING 2024-04-13 06:13:34,063 basehttp  "GET /app2/clients HTTP/1.1" 404 2976
WARNING 2024-04-13 06:13:55,440 log  Not Found: /app2/orders
WARNING 2024-04-13 06:13:55,440 basehttp  "GET /app2/orders HTTP/1.1" 404 2973
INFO 2024-04-13 06:14:57,838 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\urls.py changed, reloading.
INFO 2024-04-13 06:14:58,220 autoreload  Watching for file changes with StatReloader
WARNING 2024-04-13 06:15:05,851 log  Not Found: /app2/orders
WARNING 2024-04-13 06:15:05,852 basehttp  "GET /app2/orders HTTP/1.1" 404 2791
WARNING 2024-04-13 06:15:07,591 log  Not Found: /app2/orders
WARNING 2024-04-13 06:15:07,591 basehttp  "GET /app2/orders HTTP/1.1" 404 2791
INFO 2024-04-13 06:15:17,807 autoreload  Watching for file changes with StatReloader
INFO 2024-04-13 06:15:21,222 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-13 06:15:30,203 basehttp  "GET /app2/ HTTP/1.1" 200 1080
WARNING 2024-04-13 06:15:42,668 log  Not Found: /app2/clients
WARNING 2024-04-13 06:15:42,668 basehttp  "GET /app2/clients HTTP/1.1" 404 2794
INFO 2024-04-13 06:16:38,258 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\urls.py changed, reloading.
INFO 2024-04-13 06:16:38,657 autoreload  Watching for file changes with StatReloader
INFO 2024-04-13 06:16:41,336 basehttp  "GET /app2/clients HTTP/1.1" 301 0
INFO 2024-04-13 06:16:41,340 basehttp  "GET /app2/clients/ HTTP/1.1" 200 2
INFO 2024-04-13 06:16:52,387 basehttp  "GET /app2/clients/ HTTP/1.1" 200 2
INFO 2024-04-13 06:17:05,165 basehttp  "GET /app2/orders/ HTTP/1.1" 200 0
INFO 2024-04-13 06:41:06,665 autoreload  Watching for file changes with StatReloader
INFO 2024-04-13 06:41:10,303 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-13 06:41:23,063 log  Not Found: /app2/
WARNING 2024-04-13 06:41:23,064 basehttp  "GET /app2/ HTTP/1.1" 404 2960
INFO 2024-04-13 06:41:46,939 basehttp  "GET /app2/clients/ HTTP/1.1" 200 2
INFO 2024-04-13 23:41:10,787 autoreload  Watching for file changes with StatReloader
INFO 2024-04-13 23:41:15,461 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-13 23:41:15,560 log  Not Found: /favicon.ico
WARNING 2024-04-13 23:41:15,560 basehttp  "GET /favicon.ico HTTP/1.1" 404 2555
WARNING 2024-04-13 23:41:25,721 log  Not Found: /app2/
WARNING 2024-04-13 23:41:25,721 basehttp  "GET /app2/ HTTP/1.1" 404 2960
INFO 2024-04-13 23:41:43,927 basehttp  "GET /app2/clients/ HTTP/1.1" 200 741
INFO 2024-04-16 01:40:08,702 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 01:45:39,950 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 01:45:46,027 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-16 01:45:46,142 log  Not Found: /favicon.ico
WARNING 2024-04-16 01:45:46,142 basehttp  "GET /favicon.ico HTTP/1.1" 404 4005
INFO 2024-04-16 01:45:54,420 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 01:45:56,103 basehttp  "GET /about/ HTTP/1.1" 200 848
INFO 2024-04-16 01:45:58,192 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 01:46:05,146 basehttp  "GET / HTTP/1.1" 200 1080
ERROR 2024-04-16 01:46:46,676 log  Internal Server Error: /get-orders-by-client/
Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\django_homework\hw3_app\views.py", line 28, in get_orders_by_client
    return render(request, 'hw3_app/get_orders_by_client.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
ERROR 2024-04-16 01:46:46,684 basehttp  "GET /get-orders-by-client/ HTTP/1.1" 500 154933
INFO 2024-04-16 01:48:03,537 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\hw3_app\views.py changed, reloading.
INFO 2024-04-16 01:48:03,949 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 01:51:21,360 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 01:51:23,992 basehttp  "GET / HTTP/1.1" 200 1080
ERROR 2024-04-16 01:52:31,743 log  Internal Server Error: /get-orders-by-client/
Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\django_homework\hw3_app\views.py", line 28, in get_orders_by_client
    return render(request, 'hw3_app/get_orders_by_client.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 20: 'endblock'. Did you forget to register or load this tag?
ERROR 2024-04-16 01:52:31,748 basehttp  "GET /get-orders-by-client/ HTTP/1.1" 500 154933
INFO 2024-04-16 02:03:09,563 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 02:03:12,315 basehttp  "GET / HTTP/1.1" 200 1080
ERROR 2024-04-16 02:04:01,192 log  Internal Server Error: /get-orders-by-client/
Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\django_homework\hw3_app\views.py", line 28, in get_orders_by_client
    return render(request, 'hw3_app/get_orders_by_client.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-16 02:04:01,197 basehttp  "GET /get-orders-by-client/ HTTP/1.1" 500 134378
INFO 2024-04-16 02:08:58,256 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 02:09:00,994 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-16 02:09:29,748 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:09:29,748 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 4032
WARNING 2024-04-16 02:11:11,471 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:11:11,471 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 4032
INFO 2024-04-16 02:12:12,840 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\urls.py changed, reloading.
INFO 2024-04-16 02:12:13,253 autoreload  Watching for file changes with StatReloader
WARNING 2024-04-16 02:12:14,010 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:14,010 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:15,037 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:15,038 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:15,876 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:15,877 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:16,432 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:16,432 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:16,696 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:16,697 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:16,951 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:16,952 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:17,204 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:17,204 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:17,496 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:17,497 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:17,879 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:17,879 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:19,566 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:19,567 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:12:20,031 log  Not Found: /get_orders_by_client
WARNING 2024-04-16 02:12:20,032 basehttp  "GET /get_orders_by_client HTTP/1.1" 404 3927
WARNING 2024-04-16 02:14:49,192 log  Not Found: /hw3_app/get_orders_by_client
WARNING 2024-04-16 02:14:49,193 basehttp  "GET /hw3_app/get_orders_by_client HTTP/1.1" 404 3951
INFO 2024-04-16 02:15:33,694 basehttp  "GET /get-orders-by-client HTTP/1.1" 301 0
ERROR 2024-04-16 02:15:33,740 log  Internal Server Error: /get-orders-by-client/
Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\django_homework\hw3_app\views.py", line 28, in get_orders_by_client
    return render(request, 'hw3_app/get_orders_by_client.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\Learning\FrameworkDjango\Django_HW\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-16 02:15:33,747 basehttp  "GET /get-orders-by-client/ HTTP/1.1" 500 134378
INFO 2024-04-16 23:19:07,436 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:19:10,622 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-16 23:19:10,749 log  Not Found: /favicon.ico
WARNING 2024-04-16 23:19:10,749 basehttp  "GET /favicon.ico HTTP/1.1" 404 4893
WARNING 2024-04-16 23:20:05,360 log  Not Found: /app3/about
WARNING 2024-04-16 23:20:05,361 basehttp  "GET /app3/about HTTP/1.1" 404 4890
WARNING 2024-04-16 23:21:06,133 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:06,134 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:09,252 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:09,253 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:10,635 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:10,635 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:11,588 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:11,588 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:11,962 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:11,963 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:12,171 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:12,172 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:12,366 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:12,367 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
WARNING 2024-04-16 23:21:13,958 log  Not Found: /hw3_app/about
WARNING 2024-04-16 23:21:13,958 basehttp  "GET /hw3_app/about HTTP/1.1" 404 4899
INFO 2024-04-16 23:21:21,087 basehttp  "GET /about/ HTTP/1.1" 200 848
WARNING 2024-04-16 23:23:48,159 log  Not Found: /hw3_app/all-client-orders
WARNING 2024-04-16 23:23:48,160 basehttp  "GET /hw3_app/all-client-orders HTTP/1.1" 404 4935
WARNING 2024-04-16 23:24:07,055 log  Not Found: /all-client-orders
WARNING 2024-04-16 23:24:07,055 basehttp  "GET /all-client-orders HTTP/1.1" 404 4911
WARNING 2024-04-16 23:24:09,664 log  Not Found: /all-client-orders
WARNING 2024-04-16 23:24:09,664 basehttp  "GET /all-client-orders HTTP/1.1" 404 4911
INFO 2024-04-16 23:25:46,823 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:25:49,457 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 23:25:51,354 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 23:25:53,017 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 23:25:53,522 basehttp  "GET /about/ HTTP/1.1" 200 848
INFO 2024-04-16 23:25:54,633 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 23:26:02,750 basehttp  "GET /about/ HTTP/1.1" 200 848
WARNING 2024-04-16 23:27:09,549 log  Not Found: /hw3_app/all-client-orders
WARNING 2024-04-16 23:27:09,550 basehttp  "GET /hw3_app/all-client-orders HTTP/1.1" 404 4935
INFO 2024-04-16 23:28:34,371 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:28:37,326 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-16 23:28:49,947 log  Not Found: /app2/
WARNING 2024-04-16 23:28:49,948 basehttp  "GET /app2/ HTTP/1.1" 404 4875
INFO 2024-04-16 23:32:42,920 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\urls.py changed, reloading.
INFO 2024-04-16 23:32:43,333 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:32:50,250 autoreload  Watching for file changes with StatReloader
WARNING 2024-04-16 23:32:57,194 log  Not Found: /all-client-orders
WARNING 2024-04-16 23:32:57,194 basehttp  "GET /all-client-orders HTTP/1.1" 404 5016
WARNING 2024-04-16 23:33:13,158 log  Not Found: /app3/all-client-orders
WARNING 2024-04-16 23:33:13,159 basehttp  "GET /app3/all-client-orders HTTP/1.1" 404 6411
INFO 2024-04-16 23:40:24,503 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\settings.py changed, reloading.
INFO 2024-04-16 23:40:24,922 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:40:31,925 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:40:34,256 basehttp  "GET / HTTP/1.1" 200 1080
WARNING 2024-04-16 23:41:06,524 log  Not Found: /app3/get
WARNING 2024-04-16 23:41:06,525 basehttp  "GET /app3/get HTTP/1.1" 404 6369
WARNING 2024-04-16 23:41:21,053 log  Not Found: /app3/all-client-orders
WARNING 2024-04-16 23:41:21,054 basehttp  "GET /app3/all-client-orders HTTP/1.1" 404 6411
WARNING 2024-04-16 23:41:25,478 log  Not Found: /app3/all-client-orders
WARNING 2024-04-16 23:41:25,478 basehttp  "GET /app3/all-client-orders HTTP/1.1" 404 6411
INFO 2024-04-16 23:42:32,520 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\settings.py changed, reloading.
INFO 2024-04-16 23:42:32,941 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:43:22,336 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\settings.py changed, reloading.
INFO 2024-04-16 23:43:22,730 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:43:32,279 autoreload  D:\Learning\FrameworkDjango\Django_HW\django_homework\django_homework\settings.py changed, reloading.
INFO 2024-04-16 23:43:32,705 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:43:54,674 autoreload  Watching for file changes with StatReloader
INFO 2024-04-16 23:43:57,369 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 23:44:00,096 basehttp  "GET / HTTP/1.1" 200 1080
INFO 2024-04-16 23:44:30,842 basehttp  "GET /get-orders-by-client HTTP/1.1" 301 0
INFO 2024-04-16 23:44:30,860 basehttp  "GET /get-orders-by-client/ HTTP/1.1" 200 1592
